### ISSUE TITLE
Can't build solution with multiple nuget package sources

### ISSUE THREAD

**Issue by ray023** [BHMDotNet/ConCode.NET#1]
This issue is not related directly to ConCode.NET, but thought you might be interested in seeing it in case another user runs into the problem.

I pulled down the code and received the following error when it tried to restore the package:

> error: Unable to load the service index for source https://teklinks.pkgs.visualstudio.com/DefaultCollection/_packaging/DefaultFeed/nuget/v3/index.json.
> error:   An error occurred while sending the request.
> error:   The parameter is incorrect

I tried **dotnet restore** from the command line first but received the same error.  I had to [uncheck my customer packages](http://i.stack.imgur.com/JHfDz.jpg) first, run **dotnet restore** and then rebuild to fix.

The attached zip file contains the recorded steps from "Steps Recorder".

The error is obscure so I'm not sure if there's an actual problem with my custom packages or if this is something related to .net and nuget.  

It's interesting that a setting unrelated to your solution would prevent it from restoring properly.

[ConCode Rebuild Issue when user has multiple package sources.zip](https://github.com/BHMDotNet/ConCode.NET/files/404393/ConCode.Rebuild.Issue.when.user.has.multiple.package.sources.zip)

**Comment by helmsb** [comment]
Good catch! By default NuGet looks in %appdata%\NuGet\NuGet.config for your source settings. This is what is updated when you untick the box in Visual Studio which is why it affects ConCode.NET as well.

We should be able to override this config with a NuGet.config at our project level and check that in to prevent this issue in the future. I'll take a look tonight. 

Thanks for contributing!

**Comment by ray023** [comment]
Pulled latest, built and ran with no issues.
